### ISSUE TITLE
Enemy Spawn Point and Enemy Prefabs

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#17]
See [Gameplay -> Enemy Spawner] and [Enemies -> Enemy] on Software Design Document

**Description**
EnemySpawner: An enemy spawn framework that allows an enemy to be spawned at an area in the environment and can be seamlessly duplicated. Responsible for managing enemy spawn points and spawning enemies when it receives the main 10 second game event from the GameManager. 

Enemy: Responsible for representing the physical game object that is the enemy. Responsible for maintaining its health and acts as a capsule for other classes that represent enemy behavior.

**Acceptance Criteria**
The spawn point transforms can be added or removed in the Inspector
An Enemy prefab can be instantiated at a random or specified transform position
Enemy prefab contains an Enemy script that contains a health amount

**Subtasks**
- [x] Track spawnpoint prefabs to spawn on (may have their own script/proprties but can also just eb transform)
- [x] Enemy can spawn at spawnpoint and begin pathing

**Comment by MahadAdnanGul** [comment]
Spawn enemies using an object pool.
