### ISSUE TITLE
Weapon Models

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#30]
**Description**
3d assets of weapon models (will link concept art when available)

**References**
![Image](https://user-images.githubusercontent.com/17261899/193430181-f9842f1e-a8f5-45de-9ce2-9b070c26a571.jpg)

(will update list of weapons when available)
**Sublinks**
- [x] Shotgun
- [x] Pistol
- [x] Katana

**Comment by Makhan14** [comment]
https://easyupload.io/zwo4mm

**Comment by Makhan14** [comment]
new upload 
https://easyupload.io/3u5msk 
revolver and katana
