### ISSUE TITLE
Land Mine Item Mechanics

### ISSUE THREAD

**Issue by JohnMarman** [AMastryukov/LD51#35]
See "Items" on Software Design Document
See "Traps" on Game Design Document

**Description**
A deployable item for land mine and logic

**Acceptance Criteria**
A land mine that the player can use from their trap equipment slot and can place on the ground. Detonating when an enemy steps near it, it will damage everything in the area (enemys, player, barricades)

**Subtasks**
- [ ] Deployable land mine
- [x] Detonation and damage to nearby enemies, players, barricades

**Comment by QuantumCalzone** [comment]
Deployability is blocked by Trap Placement Controller
